export enum ViolationCode {
  PROFESSOR_COLLISION = 'PROFESSOR_COLLISION',
  CLASSROOM_COLLISION = 'CLASSROOM_COLLISION',
  SECTION_COLLISION = 'SECTION_COLLISION',
  MANDATORY_ACADEMIC_COLLISION = 'MANDATORY_ACADEMIC_COLLISION',
  INVALID_LAB_BLOCK = 'INVALID_LAB_BLOCK',
  INVALID_CLASS_LAB_DAY_BLOCK = 'INVALID_CLASS_LAB_DAY_BLOCK',
  INVALID_FIXED_ASSIGNMENT = 'INVALID_FIXED_ASSIGNMENT',
  PROFESSOR_UNAVAILABLE = 'PROFESSOR_UNAVAILABLE',
  UNASSIGNED_CLASSROOM = 'UNASSIGNED_CLASSROOM',
  UNASSIGNED_PROFESSOR = 'UNASSIGNED_PROFESSOR',
}
